# Change these first
owner: datalab-industries # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - ml-evs

workflowSchedule:
  uptime: "*/30 * * * *"

sites:
  - name: API
    url: https://avnos-datalab-api.matgenix.com/healthcheck/is_ready
  - name: App
    url: https://avnos-datalab.matgenix.com
  - name: Demo API
    url: https://demo-api.datalab-org.io/healthcheck/is_ready
  - name: Demo app
    url: https://demo.datalab-org.io/
